In [1]:
%pip install pandas joblib tensorflow

Collecting pandas
  Using cached pandas-3.0.2-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting joblib
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in ./.venv/lib/python3.13/site-packages (from tensorflow) (26.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting setuptools (from tensorflow)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.12.0 in ./.venv/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting typing_extensions>=3.6.6 (from tensorflow)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.1.2-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.4 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.80.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Using cached charset_normalizer-3.4.7-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Using cached idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.21.0->tensorflow)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.21.0->tensorflow)
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (32 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached pandas-3.0.2-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading tensorflow-2.21.0-cp313-cp313-manylinux_2_27_x86_64.whl (572.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.9/572.9 MB 9.8 MB/s  0:00:57 eta 0:00:01[36m0:00:02m
Downloading grpcio-1.80.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 10.5 MB/s  0:00:000.8 MB/s eta 0:00:01:01
Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 10.7 MB/s  0:00:001.0 MB/s eta 0:00:01
Downloading ml_dtypes-0.5.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.5 MB/s  0:00:000.9 MB/s eta 0:00:01:01
Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (215 kB)
Using cached idna-3.13-py3-none-any.whl (68 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached certifi-2026.4.22-py3-none-any.whl (135 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.14.1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.2 MB/s  0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 10.7 MB/s  0:00:02 10.8 MB/s eta 0:00:01
Using cached numpy-2.4.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Using cached termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.1.2-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (121 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (462 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, wheel, urllib3, typing_extensions, termcolor, setuptools, protobuf, opt_einsum, numpy, mdurl, joblib, idna, google_pasta, gast, charset_normalizer, certifi, absl-py, requests, pandas, optree, ml_dtypes, markdown-it-py, h5py, grpcio, astunparse, rich, keras, tensorflow
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31/31 [tensorflow]237m━ 30/31 [tensorflow]
Successfully installed absl-py-2.4.0 astunparse-1.6.3 certifi-2026.4.22 charset_normalizer-3.4.7 flatbuffers-25.12.19 gast-0.7.0 google_pasta-0.2.0 grpcio-1.80.0 h5py-3.14.0 idna-3.13 joblib-1.5.3 keras-3.14.1 libclang-18.1.1 markdown-it-py-4.2.0 mdurl-0.1.2 ml_dtypes-0.5.4 namex-0.1.0 numpy-2.4.4 opt_einsum-3.4.0 optree-0.19.1 pandas-3.0.2 protobuf-7.34.1 requests-2.33.1 rich-15.0.0 setuptools-82.0.1 tensorflow-2.21.0 termcolor-3.3.0 typing_extensions-4.15.0 urllib3-2.7.0 wheel-0.47.0 wrapt-2.1.2

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from joblib import load
from tensorflow.keras.models import load_model

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778232549.716254   12677 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778232549.725745   12677 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1778232549.820114   12677 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778232551.221681   12677 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1778232551.225880   12677 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [4]:
testing_file_path = 'data_testing/data_testing_PepPI.csv'
data_testing = pd.read_csv(testing_file_path)
data_testing

,pdb_chain,seq,Uniprot_id,prot_seq,pep_embed_0,pep_embed_1,pep_embed_2,pep_embed_3,pep_embed_4,pep_embed_5,...,prot_embed_1015,prot_embed_1016,prot_embed_1017,prot_embed_1018,prot_embed_1019,prot_embed_1020,prot_embed_1021,prot_embed_1022,prot_embed_1023,label
0,1F8R_A_16,NEEAGWYANLGPMRLPEK,Q99933,MAQRGGARRPRGDRERLGSRLRALRPGREPRQSEPPAQRGPPPSGR...,-0.039665,-0.176932,0.160456,0.258811,-0.054806,-0.038260,...,-0.157210,0.236972,-0.011630,0.131453,-0.256724,-0.013625,0.137456,-0.172659,0.034384,NaN
1,D2YW39_pep_4,WDYSDCQAK,P52298,MSGGLLKALRSDSYVELSQYRDQHFRGDNEEQEKLLKKSCTLYVGN...,0.018087,-0.061381,0.153478,0.189704,-0.177463,-0.047629,...,-0.154869,-0.041609,-0.007183,0.322257,0.115182,0.018535,-0.020584,-0.091739,0.024832,NaN
2,P81397_pep_9,WHTADCEEK,P15291,MRLREPLLSGSAAMPGASLQRACRLLVAVCALHLGVTLVYYLAGRD...,0.002181,-0.088262,0.097204,0.154111,-0.125590,-0.087029,...,-0.015929,-0.008023,0.077734,0.282099,-0.062775,-0.002993,0.031537,-0.222682,-0.109629,NaN
3,P26324_pep_4,TSWDEDIMLIR,Q9UBZ9,MRRGGWRKRAENDGWETWGGYMAAKVQKLEEQFRSDAAMQKDGTSS...,0.031314,-0.080046,0.168841,0.275760,-0.141201,-0.098943,...,-0.020682,0.072698,-0.087405,0.103340,-0.040655,-0.073017,-0.008123,-0.039313,0.051479,NaN
4,P0CB14_pep_14,ACVMAPEVNNNPTK,O60264,MSSAAEPPPPPPPESAPSKPAASIASGGSNSSNKGGPEGVAAQAVA...,-0.125661,-0.117491,0.264971,0.227269,-0.195087,0.021523,...,-0.003087,0.019465,-0.003682,0.140423,-0.036649,0.034186,0.032707,-0.002876,0.010785,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129770,A8QL52_pep_2,YDTYSTK,P08235,METKGYHSLPEGLDMERRWGQVSQAVERSSLGPTERTDENNYMEIV...,-0.133726,-0.047810,0.108349,0.416578,-0.238955,-0.079663,...,0.082729,-0.005861,-0.156237,0.142630,-0.030765,-0.092151,-0.087353,-0.095621,0.042511,NaN
129771,Q9I841_pep_2,DELADEDYVWIGLR,P21964,MPEAPPLLLAAVLLGLVLLVVLLLLLRHWGWGLCLIGWNEFILQPI...,-0.003139,-0.297337,0.074293,0.099736,0.112961,-0.010700,...,-0.080796,0.070864,0.009505,0.312381,-0.067915,-0.171866,0.209451,-0.185405,0.066686,NaN
129772,1F8R_A_1,NEEAGWYANLGPMR,P05362,MAPSSPRPALPALLVLLGALFPGPGNAQTSVSPSKVILPRGGSVLV...,0.068976,-0.062354,0.149831,0.163556,-0.201971,-0.055350,...,0.096710,0.080276,-0.014962,0.075072,-0.327599,-0.056128,0.213342,-0.074507,0.021225,NaN
129773,1F8R_A_18,LNEFSQENDNAWYFIK,O94901,MDFSRLHMYSPPQCVPENTGYTYALSSSYSSDALDFETEHKLDPVF...,-0.045588,-0.158512,0.273934,0.258862,-0.123130,-0.030399,...,0.003229,-0.005675,-0.098407,0.177947,-0.047827,-0.060041,-0.053867,-0.100174,0.067570,NaN
129774,D2YW39_pep_3,TWDEAER,O60341,MLSGKKAAAAAAAAAAAATGTEAGPGTAGGSENGSEVAAQPAGLSG...,-0.007713,-0.023497,0.192567,0.167435,-0.199780,-0.031050,...,0.005151,-0.009264,0.011298,0.154462,-0.106737,-0.016407,0.014803,-0.000131,0.005972,NaN

In [13]:
# get all columns of data_testing
data_testing.columns.tolist()

['pdb_chain',
 'seq',
 'Uniprot_id',
 'prot_seq',
 'pep_embed_0',
 'pep_embed_1',
 'pep_embed_2',
 'pep_embed_3',
 'pep_embed_4',
 'pep_embed_5',
 'pep_embed_6',
 'pep_embed_7',
 'pep_embed_8',
 'pep_embed_9',
 'pep_embed_10',
 'pep_embed_11',
 'pep_embed_12',
 'pep_embed_13',
 'pep_embed_14',
 'pep_embed_15',
 'pep_embed_16',
 'pep_embed_17',
 'pep_embed_18',
 'pep_embed_19',
 'pep_embed_20',
 'pep_embed_21',
 'pep_embed_22',
 'pep_embed_23',
 'pep_embed_24',
 'pep_embed_25',
 'pep_embed_26',
 'pep_embed_27',
 'pep_embed_28',
 'pep_embed_29',
 'pep_embed_30',
 'pep_embed_31',
 'pep_embed_32',
 'pep_embed_33',
 'pep_embed_34',
 'pep_embed_35',
 'pep_embed_36',
 'pep_embed_37',
 'pep_embed_38',
 'pep_embed_39',
 'pep_embed_40',
 'pep_embed_41',
 'pep_embed_42',
 'pep_embed_43',
 'pep_embed_44',
 'pep_embed_45',
 'pep_embed_46',
 'pep_embed_47',
 'pep_embed_48',
 'pep_embed_49',
 'pep_embed_50',
 'pep_embed_51',
 'pep_embed_52',
 'pep_embed_53',
 'pep_embed_54',
 'pep_embed_55',
 'pep_embed_56',
 'pep_embed_57',
 'pep_embed_58',
 'pep_embed_59',
 'pep_embed_60',
 'pep_embed_61',
 'pep_embed_62',
 'pep_embed_63',
 'pep_embed_64',
 'pep_embed_65',
 'pep_embed_66',
 'pep_embed_67',
 'pep_embed_68',
 'pep_embed_69',
 'pep_embed_70',
 'pep_embed_71',
 'pep_embed_72',
 'pep_embed_73',
 'pep_embed_74',
 'pep_embed_75',
 'pep_embed_76',
 'pep_embed_77',
 'pep_embed_78',
 'pep_embed_79',
 'pep_embed_80',
 'pep_embed_81',
 'pep_embed_82',
 'pep_embed_83',
 'pep_embed_84',
 'pep_embed_85',
 'pep_embed_86',
 'pep_embed_87',
 'pep_embed_88',
 'pep_embed_89',
 'pep_embed_90',
 'pep_embed_91',
 'pep_embed_92',
 'pep_embed_93',
 'pep_embed_94',
 'pep_embed_95',
 'pep_embed_96',
 'pep_embed_97',
 'pep_embed_98',
 'pep_embed_99',
 'pep_embed_100',
 'pep_embed_101',
 'pep_embed_102',
 'pep_embed_103',
 'pep_embed_104',
 'pep_embed_105',
 'pep_embed_106',
 'pep_embed_107',
 'pep_embed_108',
 'pep_embed_109',
 'pep_embed_110',
 'pep_embed_111',
 'pep_embed_112',
 'pep_embed_113',
 'pep_embed_114',
 'pep_embed_115',
 'pep_embed_116',
 'pep_embed_117',
 'pep_embed_118',
 'pep_embed_119',
 'pep_embed_120',
 'pep_embed_121',
 'pep_embed_122',
 'pep_embed_123',
 'pep_embed_124',
 'pep_embed_125',
 'pep_embed_126',
 'pep_embed_127',
 'pep_embed_128',
 'pep_embed_129',
 'pep_embed_130',
 'pep_embed_131',
 'pep_embed_132',
 'pep_embed_133',
 'pep_embed_134',
 'pep_embed_135',
 'pep_embed_136',
 'pep_embed_137',
 'pep_embed_138',
 'pep_embed_139',
 'pep_embed_140',
 'pep_embed_141',
 'pep_embed_142',
 'pep_embed_143',
 'pep_embed_144',
 'pep_embed_145',
 'pep_embed_146',
 'pep_embed_147',
 'pep_embed_148',
 'pep_embed_149',
 'pep_embed_150',
 'pep_embed_151',
 'pep_embed_152',
 'pep_embed_153',
 'pep_embed_154',
 'pep_embed_155',
 'pep_embed_156',
 'pep_embed_157',
 'pep_embed_158',
 'pep_embed_159',
 'pep_embed_160',
 'pep_embed_161',
 'pep_embed_162',
 'pep_embed_163',
 'pep_embed_164',
 'pep_embed_165',
 'pep_embed_166',
 'pep_embed_167',
 'pep_embed_168',
 'pep_embed_169',
 'pep_embed_170',
 'pep_embed_171',
 'pep_embed_172',
 'pep_embed_173',
 'pep_embed_174',
 'pep_embed_175',
 'pep_embed_176',
 'pep_embed_177',
 'pep_embed_178',
 'pep_embed_179',
 'pep_embed_180',
 'pep_embed_181',
 'pep_embed_182',
 'pep_embed_183',
 'pep_embed_184',
 'pep_embed_185',
 'pep_embed_186',
 'pep_embed_187',
 'pep_embed_188',
 'pep_embed_189',
 'pep_embed_190',
 'pep_embed_191',
 'pep_embed_192',
 'pep_embed_193',
 'pep_embed_194',
 'pep_embed_195',
 'pep_embed_196',
 'pep_embed_197',
 'pep_embed_198',
 'pep_embed_199',
 'pep_embed_200',
 'pep_embed_201',
 'pep_embed_202',
 'pep_embed_203',
 'pep_embed_204',
 'pep_embed_205',
 'pep_embed_206',
 'pep_embed_207',
 'pep_embed_208',
 'pep_embed_209',
 'pep_embed_210',
 'pep_embed_211',
 'pep_embed_212',
 'pep_embed_213',
 'pep_embed_214',
 'pep_embed_215',
 'pep_embed_216',
 'pep_embed_217',
 'pep_embed_218',
 'pep_embed_219',
 'pep_embed_220',
 'pep_embed_221',
 'pep_embed_222',
 'pep_embed_223',
 'pep_embed_224',
 'pep_embed_225',
 'pep_embed_226',
 'pep_embed_227',
 'pep_embed_228',
 'pep_embed_229',
 'pep_embed_230',
 'pep_embed_231',
 'pep_embed_232',
 'pep_embed_233',
 'pep_embed_234',
 'pep_embed_235',
 'pep_embed_236',
 'pep_embed_237',
 'pep_embed_238',
 'pep_embed_239',
 'pep_embed_240',
 'pep_embed_241',
 'pep_embed_242',
 'pep_embed_243',
 'pep_embed_244',
 'pep_embed_245',
 'pep_embed_246',
 'pep_embed_247',
 'pep_embed_248',
 'pep_embed_249',
 'pep_embed_250',
 'pep_embed_251',
 'pep_embed_252',
 'pep_embed_253',
 'pep_embed_254',
 'pep_embed_255',
 'pep_embed_256',
 'pep_embed_257',
 'pep_embed_258',
 'pep_embed_259',
 'pep_embed_260',
 'pep_embed_261',
 'pep_embed_262',
 'pep_embed_263',
 'pep_embed_264',
 'pep_embed_265',
 'pep_embed_266',
 'pep_embed_267',
 'pep_embed_268',
 'pep_embed_269',
 'pep_embed_270',
 'pep_embed_271',
 'pep_embed_272',
 'pep_embed_273',
 'pep_embed_274',
 'pep_embed_275',
 'pep_embed_276',
 'pep_embed_277',
 'pep_embed_278',
 'pep_embed_279',
 'pep_embed_280',
 'pep_embed_281',
 'pep_embed_282',
 'pep_embed_283',
 'pep_embed_284',
 'pep_embed_285',
 'pep_embed_286',
 'pep_embed_287',
 'pep_embed_288',
 'pep_embed_289',
 'pep_embed_290',
 'pep_embed_291',
 'pep_embed_292',
 'pep_embed_293',
 'pep_embed_294',
 'pep_embed_295',
 'pep_embed_296',
 'pep_embed_297',
 'pep_embed_298',
 'pep_embed_299',
 'pep_embed_300',
 'pep_embed_301',
 'pep_embed_302',
 'pep_embed_303',
 'pep_embed_304',
 'pep_embed_305',
 'pep_embed_306',
 'pep_embed_307',
 'pep_embed_308',
 'pep_embed_309',
 'pep_embed_310',
 'pep_embed_311',
 'pep_embed_312',
 'pep_embed_313',
 'pep_embed_314',
 'pep_embed_315',
 'pep_embed_316',
 'pep_embed_317',
 'pep_embed_318',
 'pep_embed_319',
 'pep_embed_320',
 'pep_embed_321',
 'pep_embed_322',
 'pep_embed_323',
 'pep_embed_324',
 'pep_embed_325',
 'pep_embed_326',
 'pep_embed_327',
 'pep_embed_328',
 'pep_embed_329',
 'pep_embed_330',
 'pep_embed_331',
 'pep_embed_332',
 'pep_embed_333',
 'pep_embed_334',
 'pep_embed_335',
 'pep_embed_336',
 'pep_embed_337',
 'pep_embed_338',
 'pep_embed_339',
 'pep_embed_340',
 'pep_embed_341',
 'pep_embed_342',
 'pep_embed_343',
 'pep_embed_344',
 'pep_embed_345',
 'pep_embed_346',
 'pep_embed_347',
 'pep_embed_348',
 'pep_embed_349',
 'pep_embed_350',
 'pep_embed_351',
 'pep_embed_352',
 'pep_embed_353',
 'pep_embed_354',
 'pep_embed_355',
 'pep_embed_356',
 'pep_embed_357',
 'pep_embed_358',
 'pep_embed_359',
 'pep_embed_360',
 'pep_embed_361',
 'pep_embed_362',
 'pep_embed_363',
 'pep_embed_364',
 'pep_embed_365',
 'pep_embed_366',
 'pep_embed_367',
 'pep_embed_368',
 'pep_embed_369',
 'pep_embed_370',
 'pep_embed_371',
 'pep_embed_372',
 'pep_embed_373',
 'pep_embed_374',
 'pep_embed_375',
 'pep_embed_376',
 'pep_embed_377',
 'pep_embed_378',
 'pep_embed_379',
 'pep_embed_380',
 'pep_embed_381',
 'pep_embed_382',
 'pep_embed_383',
 'pep_embed_384',
 'pep_embed_385',
 'pep_embed_386',
 'pep_embed_387',
 'pep_embed_388',
 'pep_embed_389',
 'pep_embed_390',
 'pep_embed_391',
 'pep_embed_392',
 'pep_embed_393',
 'pep_embed_394',
 'pep_embed_395',
 'pep_embed_396',
 'pep_embed_397',
 'pep_embed_398',
 'pep_embed_399',
 'pep_embed_400',
 'pep_embed_401',
 'pep_embed_402',
 'pep_embed_403',
 'pep_embed_404',
 'pep_embed_405',
 'pep_embed_406',
 'pep_embed_407',
 'pep_embed_408',
 'pep_embed_409',
 'pep_embed_410',
 'pep_embed_411',
 'pep_embed_412',
 'pep_embed_413',
 'pep_embed_414',
 'pep_embed_415',
 'pep_embed_416',
 'pep_embed_417',
 'pep_embed_418',
 'pep_embed_419',
 'pep_embed_420',
 'pep_embed_421',
 'pep_embed_422',
 'pep_embed_423',
 'pep_embed_424',
 'pep_embed_425',
 'pep_embed_426',
 'pep_embed_427',
 'pep_embed_428',
 'pep_embed_429',
 'pep_embed_430',
 'pep_embed_431',
 'pep_embed_432',
 'pep_embed_433',
 'pep_embed_434',
 'pep_embed_435',
 'pep_embed_436',
 'pep_embed_437',
 'pep_embed_438',
 'pep_embed_439',
 'pep_embed_440',
 'pep_embed_441',
 'pep_embed_442',
 'pep_embed_443',
 'pep_embed_444',
 'pep_embed_445',
 'pep_embed_446',
 'pep_embed_447',
 'pep_embed_448',
 'pep_embed_449',
 'pep_embed_450',
 'pep_embed_451',
 'pep_embed_452',
 'pep_embed_453',
 'pep_embed_454',
 'pep_embed_455',
 'pep_embed_456',
 'pep_embed_457',
 'pep_embed_458',
 'pep_embed_459',
 'pep_embed_460',
 'pep_embed_461',
 'pep_embed_462',
 'pep_embed_463',
 'pep_embed_464',
 'pep_embed_465',
 'pep_embed_466',
 'pep_embed_467',
 'pep_embed_468',
 'pep_embed_469',
 'pep_embed_470',
 'pep_embed_471',
 'pep_embed_472',
 'pep_embed_473',
 'pep_embed_474',
 'pep_embed_475',
 'pep_embed_476',
 'pep_embed_477',
 'pep_embed_478',
 'pep_embed_479',
 'pep_embed_480',
 'pep_embed_481',
 'pep_embed_482',
 'pep_embed_483',
 'pep_embed_484',
 'pep_embed_485',
 'pep_embed_486',
 'pep_embed_487',
 'pep_embed_488',
 'pep_embed_489',
 'pep_embed_490',
 'pep_embed_491',
 'pep_embed_492',
 'pep_embed_493',
 'pep_embed_494',
 'pep_embed_495',
 'pep_embed_496',
 'pep_embed_497',
 'pep_embed_498',
 'pep_embed_499',
 'pep_embed_500',
 'pep_embed_501',
 'pep_embed_502',
 'pep_embed_503',
 'pep_embed_504',
 'pep_embed_505',
 'pep_embed_506',
 'pep_embed_507',
 'pep_embed_508',
 'pep_embed_509',
 'pep_embed_510',
 'pep_embed_511',
 'pep_embed_512',
 'pep_embed_513',
 'pep_embed_514',
 'pep_embed_515',
 'pep_embed_516',
 'pep_embed_517',
 'pep_embed_518',
 'pep_embed_519',
 'pep_embed_520',
 'pep_embed_521',
 'pep_embed_522',
 'pep_embed_523',
 'pep_embed_524',
 'pep_embed_525',
 'pep_embed_526',
 'pep_embed_527',
 'pep_embed_528',
 'pep_embed_529',
 'pep_embed_530',
 'pep_embed_531',
 'pep_embed_532',
 'pep_embed_533',
 'pep_embed_534',
 'pep_embed_535',
 'pep_embed_536',
 'pep_embed_537',
 'pep_embed_538',
 'pep_embed_539',
 'pep_embed_540',
 'pep_embed_541',
 'pep_embed_542',
 'pep_embed_543',
 'pep_embed_544',
 'pep_embed_545',
 'pep_embed_546',
 'pep_embed_547',
 'pep_embed_548',
 'pep_embed_549',
 'pep_embed_550',
 'pep_embed_551',
 'pep_embed_552',
 'pep_embed_553',
 'pep_embed_554',
 'pep_embed_555',
 'pep_embed_556',
 'pep_embed_557',
 'pep_embed_558',
 'pep_embed_559',
 'pep_embed_560',
 'pep_embed_561',
 'pep_embed_562',
 'pep_embed_563',
 'pep_embed_564',
 'pep_embed_565',
 'pep_embed_566',
 'pep_embed_567',
 'pep_embed_568',
 'pep_embed_569',
 'pep_embed_570',
 'pep_embed_571',
 'pep_embed_572',
 'pep_embed_573',
 'pep_embed_574',
 'pep_embed_575',
 'pep_embed_576',
 'pep_embed_577',
 'pep_embed_578',
 'pep_embed_579',
 'pep_embed_580',
 'pep_embed_581',
 'pep_embed_582',
 'pep_embed_583',
 'pep_embed_584',
 'pep_embed_585',
 'pep_embed_586',
 'pep_embed_587',
 'pep_embed_588',
 'pep_embed_589',
 'pep_embed_590',
 'pep_embed_591',
 'pep_embed_592',
 'pep_embed_593',
 'pep_embed_594',
 'pep_embed_595',
 'pep_embed_596',
 'pep_embed_597',
 'pep_embed_598',
 'pep_embed_599',
 'pep_embed_600',
 'pep_embed_601',
 'pep_embed_602',
 'pep_embed_603',
 'pep_embed_604',
 'pep_embed_605',
 'pep_embed_606',
 'pep_embed_607',
 'pep_embed_608',
 'pep_embed_609',
 'pep_embed_610',
 'pep_embed_611',
 'pep_embed_612',
 'pep_embed_613',
 'pep_embed_614',
 'pep_embed_615',
 'pep_embed_616',
 'pep_embed_617',
 'pep_embed_618',
 'pep_embed_619',
 'pep_embed_620',
 'pep_embed_621',
 'pep_embed_622',
 'pep_embed_623',
 'pep_embed_624',
 'pep_embed_625',
 'pep_embed_626',
 'pep_embed_627',
 'pep_embed_628',
 'pep_embed_629',
 'pep_embed_630',
 'pep_embed_631',
 'pep_embed_632',
 'pep_embed_633',
 'pep_embed_634',
 'pep_embed_635',
 'pep_embed_636',
 'pep_embed_637',
 'pep_embed_638',
 'pep_embed_639',
 'pep_embed_640',
 'pep_embed_641',
 'pep_embed_642',
 'pep_embed_643',
 'pep_embed_644',
 'pep_embed_645',
 'pep_embed_646',
 'pep_embed_647',
 'pep_embed_648',
 'pep_embed_649',
 'pep_embed_650',
 'pep_embed_651',
 'pep_embed_652',
 'pep_embed_653',
 'pep_embed_654',
 'pep_embed_655',
 'pep_embed_656',
 'pep_embed_657',
 'pep_embed_658',
 'pep_embed_659',
 'pep_embed_660',
 'pep_embed_661',
 'pep_embed_662',
 'pep_embed_663',
 'pep_embed_664',
 'pep_embed_665',
 'pep_embed_666',
 'pep_embed_667',
 'pep_embed_668',
 'pep_embed_669',
 'pep_embed_670',
 'pep_embed_671',
 'pep_embed_672',
 'pep_embed_673',
 'pep_embed_674',
 'pep_embed_675',
 'pep_embed_676',
 'pep_embed_677',
 'pep_embed_678',
 'pep_embed_679',
 'pep_embed_680',
 'pep_embed_681',
 'pep_embed_682',
 'pep_embed_683',
 'pep_embed_684',
 'pep_embed_685',
 'pep_embed_686',
 'pep_embed_687',
 'pep_embed_688',
 'pep_embed_689',
 'pep_embed_690',
 'pep_embed_691',
 'pep_embed_692',
 'pep_embed_693',
 'pep_embed_694',
 'pep_embed_695',
 'pep_embed_696',
 'pep_embed_697',
 'pep_embed_698',
 'pep_embed_699',
 'pep_embed_700',
 'pep_embed_701',
 'pep_embed_702',
 'pep_embed_703',
 'pep_embed_704',
 'pep_embed_705',
 'pep_embed_706',
 'pep_embed_707',
 'pep_embed_708',
 'pep_embed_709',
 'pep_embed_710',
 'pep_embed_711',
 'pep_embed_712',
 'pep_embed_713',
 'pep_embed_714',
 'pep_embed_715',
 'pep_embed_716',
 'pep_embed_717',
 'pep_embed_718',
 'pep_embed_719',
 'pep_embed_720',
 'pep_embed_721',
 'pep_embed_722',
 'pep_embed_723',
 'pep_embed_724',
 'pep_embed_725',
 'pep_embed_726',
 'pep_embed_727',
 'pep_embed_728',
 'pep_embed_729',
 'pep_embed_730',
 'pep_embed_731',
 'pep_embed_732',
 'pep_embed_733',
 'pep_embed_734',
 'pep_embed_735',
 'pep_embed_736',
 'pep_embed_737',
 'pep_embed_738',
 'pep_embed_739',
 'pep_embed_740',
 'pep_embed_741',
 'pep_embed_742',
 'pep_embed_743',
 'pep_embed_744',
 'pep_embed_745',
 'pep_embed_746',
 'pep_embed_747',
 'pep_embed_748',
 'pep_embed_749',
 'pep_embed_750',
 'pep_embed_751',
 'pep_embed_752',
 'pep_embed_753',
 'pep_embed_754',
 'pep_embed_755',
 'pep_embed_756',
 'pep_embed_757',
 'pep_embed_758',
 'pep_embed_759',
 'pep_embed_760',
 'pep_embed_761',
 'pep_embed_762',
 'pep_embed_763',
 'pep_embed_764',
 'pep_embed_765',
 'pep_embed_766',
 'pep_embed_767',
 'pep_embed_768',
 'pep_embed_769',
 'pep_embed_770',
 'pep_embed_771',
 'pep_embed_772',
 'pep_embed_773',
 'pep_embed_774',
 'pep_embed_775',
 'pep_embed_776',
 'pep_embed_777',
 'pep_embed_778',
 'pep_embed_779',
 'pep_embed_780',
 'pep_embed_781',
 'pep_embed_782',
 'pep_embed_783',
 'pep_embed_784',
 'pep_embed_785',
 'pep_embed_786',
 'pep_embed_787',
 'pep_embed_788',
 'pep_embed_789',
 'pep_embed_790',
 'pep_embed_791',
 'pep_embed_792',
 'pep_embed_793',
 'pep_embed_794',
 'pep_embed_795',
 'pep_embed_796',
 'pep_embed_797',
 'pep_embed_798',
 'pep_embed_799',
 'pep_embed_800',
 'pep_embed_801',
 'pep_embed_802',
 'pep_embed_803',
 'pep_embed_804',
 'pep_embed_805',
 'pep_embed_806',
 'pep_embed_807',
 'pep_embed_808',
 'pep_embed_809',
 'pep_embed_810',
 'pep_embed_811',
 'pep_embed_812',
 'pep_embed_813',
 'pep_embed_814',
 'pep_embed_815',
 'pep_embed_816',
 'pep_embed_817',
 'pep_embed_818',
 'pep_embed_819',
 'pep_embed_820',
 'pep_embed_821',
 'pep_embed_822',
 'pep_embed_823',
 'pep_embed_824',
 'pep_embed_825',
 'pep_embed_826',
 'pep_embed_827',
 'pep_embed_828',
 'pep_embed_829',
 'pep_embed_830',
 'pep_embed_831',
 'pep_embed_832',
 'pep_embed_833',
 'pep_embed_834',
 'pep_embed_835',
 'pep_embed_836',
 'pep_embed_837',
 'pep_embed_838',
 'pep_embed_839',
 'pep_embed_840',
 'pep_embed_841',
 'pep_embed_842',
 'pep_embed_843',
 'pep_embed_844',
 'pep_embed_845',
 'pep_embed_846',
 'pep_embed_847',
 'pep_embed_848',
 'pep_embed_849',
 'pep_embed_850',
 'pep_embed_851',
 'pep_embed_852',
 'pep_embed_853',
 'pep_embed_854',
 'pep_embed_855',
 'pep_embed_856',
 'pep_embed_857',
 'pep_embed_858',
 'pep_embed_859',
 'pep_embed_860',
 'pep_embed_861',
 'pep_embed_862',
 'pep_embed_863',
 'pep_embed_864',
 'pep_embed_865',
 'pep_embed_866',
 'pep_embed_867',
 'pep_embed_868',
 'pep_embed_869',
 'pep_embed_870',
 'pep_embed_871',
 'pep_embed_872',
 'pep_embed_873',
 'pep_embed_874',
 'pep_embed_875',
 'pep_embed_876',
 'pep_embed_877',
 'pep_embed_878',
 'pep_embed_879',
 'pep_embed_880',
 'pep_embed_881',
 'pep_embed_882',
 'pep_embed_883',
 'pep_embed_884',
 'pep_embed_885',
 'pep_embed_886',
 'pep_embed_887',
 'pep_embed_888',
 'pep_embed_889',
 'pep_embed_890',
 'pep_embed_891',
 'pep_embed_892',
 'pep_embed_893',
 'pep_embed_894',
 'pep_embed_895',
 'pep_embed_896',
 'pep_embed_897',
 'pep_embed_898',
 'pep_embed_899',
 'pep_embed_900',
 'pep_embed_901',
 'pep_embed_902',
 'pep_embed_903',
 'pep_embed_904',
 'pep_embed_905',
 'pep_embed_906',
 'pep_embed_907',
 'pep_embed_908',
 'pep_embed_909',
 'pep_embed_910',
 'pep_embed_911',
 'pep_embed_912',
 'pep_embed_913',
 'pep_embed_914',
 'pep_embed_915',
 'pep_embed_916',
 'pep_embed_917',
 'pep_embed_918',
 'pep_embed_919',
 'pep_embed_920',
 'pep_embed_921',
 'pep_embed_922',
 'pep_embed_923',
 'pep_embed_924',
 'pep_embed_925',
 'pep_embed_926',
 'pep_embed_927',
 'pep_embed_928',
 'pep_embed_929',
 'pep_embed_930',
 'pep_embed_931',
 'pep_embed_932',
 'pep_embed_933',
 'pep_embed_934',
 'pep_embed_935',
 'pep_embed_936',
 'pep_embed_937',
 'pep_embed_938',
 'pep_embed_939',
 'pep_embed_940',
 'pep_embed_941',
 'pep_embed_942',
 'pep_embed_943',
 'pep_embed_944',
 'pep_embed_945',
 'pep_embed_946',
 'pep_embed_947',
 'pep_embed_948',
 'pep_embed_949',
 'pep_embed_950',
 'pep_embed_951',
 'pep_embed_952',
 'pep_embed_953',
 'pep_embed_954',
 'pep_embed_955',
 'pep_embed_956',
 'pep_embed_957',
 'pep_embed_958',
 'pep_embed_959',
 'pep_embed_960',
 'pep_embed_961',
 'pep_embed_962',
 'pep_embed_963',
 'pep_embed_964',
 'pep_embed_965',
 'pep_embed_966',
 'pep_embed_967',
 'pep_embed_968',
 'pep_embed_969',
 'pep_embed_970',
 'pep_embed_971',
 'pep_embed_972',
 'pep_embed_973',
 'pep_embed_974',
 'pep_embed_975',
 'pep_embed_976',
 'pep_embed_977',
 'pep_embed_978',
 'pep_embed_979',
 'pep_embed_980',
 'pep_embed_981',
 'pep_embed_982',
 'pep_embed_983',
 'pep_embed_984',
 'pep_embed_985',
 'pep_embed_986',
 'pep_embed_987',
 'pep_embed_988',
 'pep_embed_989',
 'pep_embed_990',
 'pep_embed_991',
 'pep_embed_992',
 'pep_embed_993',
 'pep_embed_994',
 'pep_embed_995',
 ...]

In [5]:
X_test = data_testing.drop(columns=['label', 'pdb_chain', 'seq', 'Uniprot_id', 'prot_seq'])
X_test

,pep_embed_0,pep_embed_1,pep_embed_2,pep_embed_3,pep_embed_4,pep_embed_5,pep_embed_6,pep_embed_7,pep_embed_8,pep_embed_9,...,prot_embed_1014,prot_embed_1015,prot_embed_1016,prot_embed_1017,prot_embed_1018,prot_embed_1019,prot_embed_1020,prot_embed_1021,prot_embed_1022,prot_embed_1023
0,-0.039665,-0.176932,0.160456,0.258811,-0.054806,-0.038260,-0.109457,-0.246985,-0.123477,-0.004145,...,0.009004,-0.157210,0.236972,-0.011630,0.131453,-0.256724,-0.013625,0.137456,-0.172659,0.034384
1,0.018087,-0.061381,0.153478,0.189704,-0.177463,-0.047629,-0.193332,-0.255559,-0.098111,-0.228617,...,-0.153087,-0.154869,-0.041609,-0.007183,0.322257,0.115182,0.018535,-0.020584,-0.091739,0.024832
2,0.002181,-0.088262,0.097204,0.154111,-0.125590,-0.087029,-0.169361,-0.289908,-0.111464,-0.163098,...,-0.123476,-0.015929,-0.008023,0.077734,0.282099,-0.062775,-0.002993,0.031537,-0.222682,-0.109629
3,0.031314,-0.080046,0.168841,0.275760,-0.141201,-0.098943,-0.144750,-0.448282,-0.122061,-0.266704,...,-0.018598,-0.020682,0.072698,-0.087405,0.103340,-0.040655,-0.073017,-0.008123,-0.039313,0.051479
4,-0.125661,-0.117491,0.264971,0.227269,-0.195087,0.021523,-0.145403,-0.332731,-0.176187,-0.053216,...,-0.158684,-0.003087,0.019465,-0.003682,0.140423,-0.036649,0.034186,0.032707,-0.002876,0.010785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129770,-0.133726,-0.047810,0.108349,0.416578,-0.238955,-0.079663,-0.218623,-0.346907,-0.116319,-0.143851,...,0.069755,0.082729,-0.005861,-0.156237,0.142630,-0.030765,-0.092151,-0.087353,-0.095621,0.042511
129771,-0.003139,-0.297337,0.074293,0.099736,0.112961,-0.010700,-0.106452,-0.361280,-0.011168,-0.081409,...,-0.083046,-0.080796,0.070864,0.009505,0.312381,-0.067915,-0.171866,0.209451,-0.185405,0.066686
129772,0.068976,-0.062354,0.149831,0.163556,-0.201971,-0.055350,-0.221493,-0.222738,-0.154032,-0.284393,...,0.012021,0.096710,0.080276,-0.014962,0.075072,-0.327599,-0.056128,0.213342,-0.074507,0.021225
129773,-0.045588,-0.158512,0.273934,0.258862,-0.123130,-0.030399,-0.200264,-0.330993,-0.091308,-0.110055,...,-0.066844,0.003229,-0.005675,-0.098407,0.177947,-0.047827,-0.060041,-0.053867,-0.100174,0.067570
129774,-0.007713,-0.023497,0.192567,0.167435,-0.199780,-0.031050,-0.211308,-0.493369,-0.071505,-0.057797,...,-0.053394,0.005151,-0.009264,0.011298,0.154462,-0.106737,-0.016407,0.014803,-0.000131,0.005972

In [6]:
model_path = "best_model_auc_0.8748.h5"
loaded_model = load_model(model_path)

E0000 00:00:1778232654.059594   12677 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1778232654.060341   14813 cuda_executor.cc:1755] Failed to determine cuDNN version (Note that this is expected if the application doesn't link the cuDNN plugin): INTERNAL: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
W0000 00:00:1778232654.079326   12677 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [7]:
# Prediksi probabilitas
predictions_probabilities = loaded_model.predict(X_test)

4056/4056 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

In [9]:
threshold = 0.9
predictions_classes = (predictions_probabilities >= threshold).astype(int)

results_df = data_testing[['pdb_chain', 'seq', 'Uniprot_id', 'prot_seq']].copy()
results_df['predict_probability'] = predictions_probabilities.flatten()
results_df['predict'] = predictions_classes.flatten()
results_df

,pdb_chain,seq,Uniprot_id,prot_seq,predict_probability,predict
0,1F8R_A_16,NEEAGWYANLGPMRLPEK,Q99933,MAQRGGARRPRGDRERLGSRLRALRPGREPRQSEPPAQRGPPPSGR...,0.122905,0
1,D2YW39_pep_4,WDYSDCQAK,P52298,MSGGLLKALRSDSYVELSQYRDQHFRGDNEEQEKLLKKSCTLYVGN...,0.018813,0
2,P81397_pep_9,WHTADCEEK,P15291,MRLREPLLSGSAAMPGASLQRACRLLVAVCALHLGVTLVYYLAGRD...,0.182411,0
3,P26324_pep_4,TSWDEDIMLIR,Q9UBZ9,MRRGGWRKRAENDGWETWGGYMAAKVQKLEEQFRSDAAMQKDGTSS...,0.408647,0
4,P0CB14_pep_14,ACVMAPEVNNNPTK,O60264,MSSAAEPPPPPPPESAPSKPAASIASGGSNSSNKGGPEGVAAQAVA...,0.286674,0
...,...,...,...,...,...,...
129770,A8QL52_pep_2,YDTYSTK,P08235,METKGYHSLPEGLDMERRWGQVSQAVERSSLGPTERTDENNYMEIV...,0.614200,0
129771,Q9I841_pep_2,DELADEDYVWIGLR,P21964,MPEAPPLLLAAVLLGLVLLVVLLLLLRHWGWGLCLIGWNEFILQPI...,0.230656,0
129772,1F8R_A_1,NEEAGWYANLGPMR,P05362,MAPSSPRPALPALLVLLGALFPGPGNAQTSVSPSKVILPRGGSVLV...,0.847610,0
129773,1F8R_A_18,LNEFSQENDNAWYFIK,O94901,MDFSRLHMYSPPQCVPENTGYTYALSSSYSSDALDFETEHKLDPVF...,0.662444,0
129774,D2YW39_pep_3,TWDEAER,O60341,MLSGKKAAAAAAAAAAAATGTEAGPGTAGGSENGSEVAAQPAGLSG...,0.659324,0

In [10]:
results_df = results_df.sort_values(by='predict_probability', ascending=False).reset_index(drop=True)
results_df

,pdb_chain,seq,Uniprot_id,prot_seq,predict_probability,predict
0,P30403_pep_9,LRPGAQCGEGLCCEQCK,P00749,MRALLARLLLCVLVVSDSKGSNELHQVPSNCDCLNGGTCVSNKYFS...,0.989804,1
1,P30403_pep_9,LRPGAQCGEGLCCEQCK,Q8NBP7,MGTVSSRRSWWPLPLLLLLLLLLGPAGARAQEDEDGDYEELVLALR...,0.988754,1
2,P30403_pep_9,LRPGAQCGEGLCCEQCK,Q9Y5Y6,MGSDRARKGGGGPKDFGAGLKYNSRHEKVNGLEEGVEFLPVNNVKK...,0.988676,1
3,P0CB14_pep_7,DFDGNTVGLAFVGGICNEKYCAGVVQDHTK,Q9NWT6,MAATAAEAVASGSGEPREEAGALGPAWDESQLRSYSFPTRPIPRLS...,0.988302,1
4,P30403_pep_9,LRPGAQCGEGLCCEQCK,P09668,MWATLPLLCAGAWLLGVPVCGAAELCVNSLEKFHFKSWMSKHRKTY...,0.988171,1
...,...,...,...,...,...,...
129770,A8QL52_pep_1,YPVKPSEEGK,P00403,MAHAAQVGLQDATSPIMEELITFHDHALMIIFLICFLVLYALFLTL...,0.000802,0
129771,1F8R_A_22,KDPGLLK,P00156,MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQIT...,0.000774,0
129772,1F8R_A_5,VTVVYETLSK,P00156,MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQIT...,0.000719,0
129773,A8QL52_pep_1,YPVKPSEEGK,P00156,MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQIT...,0.000647,0
129774,1F8R_A_6,SAGQLYEESLGK,P00156,MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQIT...,0.000637,0